name: marked
description: A simple Markdown parser for Dart. Create your own custom Markdown syntax.
version: 0.0.2
repository: https://github.com/DrafaKiller/Markdown-dart
issue_tracker: https://github.com/DrafaKiller/Markdown-dart/issues

environment:
  sdk: '>=2.18.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
